# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OAMQGIS3
                                 A QGIS plugin
 Open Aerial Map Plugin for QGIS3
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-02-14
        copyright            : (C) 2019 by yojiyojiyoji
        email                : yoji.salut@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OAMQGIS3 class from file OAMQGIS3.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .oam_qgis3 import OAMQGIS3
    return OAMQGIS3(iface)
